### ISSUE TITLE
getName is not defined

### ISSUE THREAD

**Issue by cvalues** [dargmuesli/nuxt-cookie-control#108]
### Environment

Newest nuxt 2.X

### Reproduction

Clicking acceptNecessary throws this error

### Describe the bug

getName is not defined
    at eval (nuxt-cookie-control.js:138:1)
    at Array.map (<anonymous>)
    at acceptNecessary (nuxt-cookie-control.js:138:1)
    at invokeWithErrorHandling (vue.common.dev.js:3636:1)
    at HTMLButtonElement.invoker (vue.common.dev.js:1483:1)
    at original._wrapper (vue.common.dev.js:7931:1)

### Additional context

    necessary: [
      {
        //if multilanguage
        name: {
          en: 'Default Cookies',
          de: 'Standard-Cookies'
        },
        //else
        //name:  'Default Cookies',
        //if multilanguage
        description: {
          en:  'These cookies are required for the operation of the site.',
          de:  'Diese Cookies werden zum Betrieb der Seite benötigt.'
        },
        //else
        //description:  'Used for cookie control.',
        cookies: ['cookie_control_consent', 'cookie_control_enabled_cookies']
      }
    ],

**Comment by dargmuesli** [comment]
Hey there, this module only supports Nuxt 3! For Nuxt 2, please use `nuxt-cookie-control` < v3.

**Comment by cvalues** [comment]
Hi,

we are using <3, the banner did work in the past.

"nuxt-cookie-control": "^1.9.91",

**Comment by dargmuesli** [comment]
For versions below v3, please report issues to https://gitlab.com/broj42/nuxt-cookie-control/-/issues :heart:

**Comment by cvalues** [comment]
okay, thank you.
