### ISSUE TITLE
missing useNuxtApp import in components

### ISSUE THREAD

**Issue by huang-julien** [dargmuesli/nuxt-cookie-control#109]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.16.1
- Nuxt Version:     3.6.2
- Nitro Version:    2.5.2
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-h3vzyp?file=nuxt.config.ts,app.vue

### Describe the bug

There's some imports missing in components

**Comment by smil2k** [comment]
Wow, you just saved my day. Thank you for this release!
