### ISSUE TITLE
Excessive stack depth comparing types 'NuxtModule<ModuleOptions>' and 'NuxtModule<ModuleOptions>'.

### ISSUE THREAD

**Issue by matteomejia** [dargmuesli/nuxt-cookie-control#142]
### Environment

- Operating System: Darwin
- Node Version:     v18.17.1
- Nuxt Version:     3.7.3
- CLI Version:      3.8.4
- Nitro Version:    2.6.3
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      devtools, modules
- Runtime Modules:  @dargmuesli/nuxt-cookie-control@6.4.2
- Build Modules:    -

### Reproduction

Create a new Nuxt 3 project with `nuxi` and add `@dargmuesli/nuxt-cookie-control` to the modules.

### Describe the bug

Installing the module in a project with Nuxt 3 `v 3.7.3` causes the following TS errors:

* `Excessive stack depth comparing types 'NuxtModule<ModuleOptions>' and 'NuxtModule<ModuleOptions>'. ts(2321)`
* `Type instantiation is excessively deep and possibly infinite. ts(2589)`

Looking at the `yarn.lock` file, it seems the module causes a conflict with the dependency `@nuxt/kit`, where two versions are installed: `3.7.1` and `3.7.3`

**Comment by urbgimtam** [comment]
Suffering the same issue after installing the module.

**Comment by dargmuesli** [comment]
Please follow the issue template and link a minimal reproduction using https://stackblitz.com/github/dargmuesli/nuxt-cookie-control?file=playground%2Fapp.vue

If I may guess: make sure you run `nuxi upgrade` whenever you upgrade Nuxt.

**Comment by matteomejia** [comment]
Made a reproduction here: [link](https://stackblitz.com/edit/nuxt-starter-hnivgw?file=nuxt.config.ts). Make sure to run `npm run postinstall` and `npx nuxi typecheck`.

The issue template, AFAIK, may not be able to reproduce the bug, since it always uses the latest Nuxt version to build the module.

**Comment by dargmuesli** [comment]
Please try `v6.4.3` when it's released shortly. I'd keep this issue open a bit longer until I'm sure my Renovate configuration does not pin the dependencies again.

**Comment by matteomejia** [comment]
I can confirm the issue is gone now that the versions match.

**Comment by dargmuesli** [comment]
Updated reproduction: https://stackblitz.com/edit/nuxt-starter-gqkq1b?file=package.json
I guess that issue requires further monitoring until I'm sure I understand the best way to configure dependency versions for this project.
