### ISSUE TITLE
I want thai(th) languange

### ISSUE THREAD

**Issue by webmaster-dexontechnology** [dargmuesli/nuxt-cookie-control#163]
### Describe the feature

I want Thai language Could you please add it to me? Thanks.

### Additional information

- [X] Would you be willing to help implement this feature?

### Final checks

- [X] Check existing [discussions](https://github.com/nuxt/framework/discussions) and [issues](https://github.com/nuxt/framework/issues).

**Comment by dargmuesli** [comment]
As I do not speak Thai, I cannot. Are you able to translate?

**Comment by dargmuesli** [comment]
Closing for now. Pull request welcome! :heart:
