### ISSUE TITLE
isConsentGiven still false after accept necessary is clicked

### ISSUE THREAD

**Issue by hunyan-io** [dargmuesli/nuxt-cookie-control#183]
### Environment

- Operating System: Windows_NT
- Node Version:     v18.16.0
- Nuxt Version:     3.8.0
- CLI Version:      3.9.1
- Nitro Version:    2.7.0
- Package Manager:  npm@9.5.1
- Builder:          -
- User Config:      devtools, devServer, css, modules, ui, googleFonts, cookieControl, build, typescript, imports, runtimeConfig
- Runtime Modules:  @nuxt/ui@2.10.0, @nuxtjs/google-fonts@3.0.2, @vueuse/nuxt@10.5.0, @dargmuesli/nuxt-cookie-control@7.1.4
- Build Modules:    -

### Reproduction

The issue can be reproduced in the existing reproduction template ( https://stackblitz.com/github/dargmuesli/nuxt-cookie-control?file=playground%2Fapp.vue )

### Describe the bug

Click "Customize" -> Click "Decline All" (accept necessary)
Expected behavior: isConsentGiven is set to true, cookie bar is dismissed
Actual behavior: isConsentGiven still false, cookie bar still there

I hope the actual behavior is not the intended one. It doesn't make sense as I can't dismiss the cookie bar by accepting necessary cookies only.
I'm willing to open a PR once it's confirmed this is not intentional

**Comment by dargmuesli** [comment]
This is already tracked in https://github.com/dargmuesli/nuxt-cookie-control/issues/131, a PR as described there is welcome!
