### ISSUE TITLE
docs: document migration and reactive state

### ISSUE THREAD

**Issue by maxleistner** [dargmuesli/nuxt-cookie-control#19]
How can i run a script if the cookie gets accepted. There should be an accepted function but it does not work. 
Everything else works fine. 

```
[
      "@dargmuesli/nuxt-cookie-control",
      {
        locales: ["de", "en"],
        cookies: {
          optional: [
            {
              id: "ga",
              name: {
                de: "Google Analytics ist ein von Google angebotener Webanalysedienst, der den Website-Verkehr verfolgt und meldet.",
                en: "Google Analytics",
              },
              src: "https://www.googletagmanager.com/gtag/js?id=G-*****",
              async: true,
              targetCookieIds: ["_ga", "*****", "_gid"],
              accepted: () => {
                console.log("TEST");
                window.dataLayer = window.dataLayer || [];
                function gtag() {
                  dataLayer.push(arguments);
                }
                gtag("js", new Date());

                gtag("config", "G-*****");
              },
            },
          ],
        },
      },
    ],
    ```

**Comment by dargmuesli** [comment]
See https://github.com/dargmuesli/nuxt-cookie-control/discussions/17#discussioncomment-4608729. I'd like to add better documentation on that to the README and keep this issue open until that's done.

**Comment by maxleistner** [comment]
> See [#17 (comment)](https://github.com/dargmuesli/nuxt-cookie-control/discussions/17#discussioncomment-4608729). I'd like to add better documentation on that to the README and keep this issue open until that's done.

Ok got it. But then i still need to reload the page once, because after running the function the code is inserted, but google analytics does not fire any cookies or code. Somehow i need to trigger the Accept Button. The Decline Button in the overlay is triggering a reload, why not the accept button?

**Comment by dargmuesli** [comment]
Let's talk about the reload topic in the corresponding issue #20.

**Comment by dargmuesli** [comment]
https://github.com/dargmuesli/nuxt-cookie-control/releases/tag/2.0.0
