### ISSUE TITLE
add support for lists in description

### ISSUE THREAD

**Issue by jseerig** [dargmuesli/nuxt-cookie-control#196]
### Describe the feature

I would like to add a list as a cookie description. 
For example I would like it to display like this: 
<img width="832" alt="Bildschirmfoto 2024-03-14 um 11 33 47" src="https://github.com/dargmuesli/nuxt-cookie-control/assets/62983185/1b568a8e-4bbd-4903-8daf-2b6fe30e4f5d">

### Additional information

- [x] Would you be willing to help implement this feature?

### Final checks

- [X] Check existing [discussions](https://github.com/nuxt/framework/discussions) and [issues](https://github.com/nuxt/framework/issues).

**Comment by dargmuesli** [comment]
You can use [the slot named `cookie`](https://github.com/dargmuesli/nuxt-cookie-control?tab=readme-ov-file#cookie) to customize how cookie metadata is displayed.

**Comment by jseerig** [comment]
And how can I only customize the description? I want to keep the headings and toggles like there are.

**Comment by dargmuesli** [comment]
You can use the same code this module uses and customize only the parts you're interested in: https://github.com/dargmuesli/nuxt-cookie-control/blob/master/src/runtime/components/CookieControl.vue#L80-L149

**Comment by develth** [comment]
i also wanted to use that, but `cookieType` is not available and we have a duplicate code just to append something in the end.
Additional Slot would be really helpful, @dargmuesli

**Comment by dargmuesli** [comment]
Please explain how `cookieType` is not available, e.g. with a minimal reproduction. You can suggest an additional slot placement by submitting exemplary code.

**Comment by develth** [comment]
> Please explain how `cookieType` is not available, e.g. with a minimal reproduction. You can suggest an additional slot placement by submitting exemplary code.

When using `<template #cookie="{ cookie }">`, [Slot provides only `cookie`](https://github.com/dargmuesli/nuxt-cookie-control/blob/master/src/runtime/components/CookieControl.vue#L79), `cookie` does not include `cookieType`.
Really needs a minimal reproduction for that?

**Comment by dargmuesli** [comment]
What about [importing cookieType](https://github.com/dargmuesli/nuxt-cookie-control/blob/49d7db22b8576a351213a891ffa3f28551c0bc52/src/runtime/components/CookieControl.vue#L202) as it's done in that file?

**Comment by develth** [comment]
I´m not talking about the `CookieType` type, it´s about `cookieType` variable...

**Comment by dargmuesli** [comment]
[`cookieType` is set to `CookieType`'s values](https://github.com/dargmuesli/nuxt-cookie-control/blob/49d7db22b8576a351213a891ffa3f28551c0bc52/src/runtime/components/CookieControl.vue#L64).

**Comment by develth** [comment]
🤣 i step out here. waste of time...

**Comment by develth** [comment]
https://stackblitz.com/edit/nuxt-starter-tnvnfn?file=app.vue

**Comment by dargmuesli** [comment]
@develth I do not appreciate the comment you added and deleted and the passive aggressive wording in the new comment / stackblitz. This is free software without charge that people spend their time on voluntarily. It's always possible to raise a PR to add improvements without laughing at others trying to help or to sponsor contributors as a motivation to improve things without implying they're hindering. Future interactions in a similar manner will not be accepted and I'd need a reason to continue this thread.

**Comment by dargmuesli** [comment]
A certain - maybe larger than expected - amount of information is necessary to understand the limitations that others research. If you feel ignored, please voice that concern instead of commenting in a desperate style.

> you finally invested some time

Again, I do not appreciate judgement on the time spent previously. I'll moderate this now.
