### ISSUE TITLE
feat: remove page reload

### ISSUE THREAD

**Issue by maxleistner** [dargmuesli/nuxt-cookie-control#20]
How can i force a page reload after accepting/declining cookies? Thanks

**Comment by dargmuesli** [comment]
Just out of curiosity, before I answer with a technical solution: what usecase do you have that requires a full page reload? Do you really need a full page reload or would a callback function or watcher work as well for you?

**Comment by maxleistner** [comment]
I want to implement google analytics (4). And i guess that the correct tracking will only work after a reload. I could not test it till now as of my previous ticket :)

**Comment by maxleistner** [comment]
Can you edit this line so i can pass a setting to enable reload: true?
https://github.com/dargmuesli/nuxt-cookie-control/blob/master/src/runtime/components/CookieControl.vue#L18

**Comment by dargmuesli** [comment]
Actually, neither should trigger a reload. It shouldn't be up to the library to decide when to reload but up to the depending projects. They are supposed to listen to changes in reactive state and trigger a reload if needed.
I simply have not removed the reload from this fork yet because I was not sure about that yet, but now I am. No need to wait for me to remove it though, as the reactive state can be watched already. Will close this issue once I removed it though.

**Comment by maxleistner** [comment]
Ok i get what you mean, but if I include a script like vue-gtag, it does not do a reload. So I would need to trigger it. But of course I only want it to be reloaded once. The click of the Accept button is in my opinion the best place to trigger it. How would you do it? Due to DSGVO it need to be disabled from the start and only be activated after ACCEPT. what's your solution for this?

**Comment by dargmuesli** [comment]
Again, the accept button click has or will have no authority over demanding a page reload. Thus one should not search for ways to trigger a reload based on the button being clicked. You got it correct that you have to react to the cookie being enabled, though! How you do that is what I already explained and what I will add to the readme in #19: https://github.com/dargmuesli/nuxt-cookie-control/discussions/17#discussioncomment-4608729

**Comment by maxleistner** [comment]
Not exactly. You just explain in #17 how to trigger a function. But the triggering of the gtag function does not lead to a ga cookie. The function gets executed, but no hit on ga is send to ga. After reloading the page ga sends a hit and starts tracking. So how would you do that without a reload? That part you did not explain. As this is in your opinion not part of your script you can just tell me that its not your business. Otherwise i would be thankful for help.

**Comment by dargmuesli** [comment]
```ts
const cookieControl = useCookieControl()

if (cookieControl.cookiesEnabledIds.value.includes('google-analytics')) {
    window.location.reload()
}
```

Execute it whenever you see it fits, e.g. in a client side plugin.

**Comment by maxleistner** [comment]
> ```ts
> const cookieControl = useCookieControl()
> 
> if (cookieControl.cookiesEnabledIds.value.includes('google-analytics')) {
>     window.location.reload()
> }
> ```
> 
> Execute it whenever you see it fits, e.g. in a client side plugin.

This would just keep reloading the page...again and again....

**Comment by dargmuesli** [comment]
Then you might listen for its addition only.

```ts
// pseudocode
watch(
    () => cookieControl.cookiesEnabledIds.value,
    (current, previous) => {
        // if previous.cookiesEnabledIds does not include google-analytics and current.cookiesEnabledIds does
        window.location.reload()

    },
    { deep: true }
)
```

**Comment by dargmuesli** [comment]
The v3 beta is released. Feel free to try it out!

**Comment by dargmuesli** [comment]
7631391b8c06dc7bff897aa76814a02a27d5d74f
