### ISSUE TITLE
Modify cookie modal

### ISSUE THREAD

**Issue by FrazeColder** [dargmuesli/nuxt-cookie-control#201]
### Describe the feature

Hey there,

thank you for this great package! I really would like to use it, but have some minor changes to suggest.

As in the cookie bar, I would like to have a modal which has the following button options: 
1. "Accept all Cookies"
2. "Individual cookie settings" 

That should look like this in the end:
<img width="419" alt="grafik" src="https://github.com/dargmuesli/nuxt-cookie-control/assets/18104426/2d6f1730-9b60-4933-8988-942ac6b7735c">

When I press button number 1 the cookie modal closes and accepts all cookies.

When I press the second button the modal should expand like Borlabs Cookies for WordPress showing individual cookie settings and a save as well as an accept all button. Like this:

<img width="809" alt="grafik" src="https://github.com/dargmuesli/nuxt-cookie-control/assets/18104426/47056020-f418-41a4-94b7-f1826627fc71">

Kind regards and thank you!

**Comment by dargmuesli** [comment]
What changes exactly do you request to be made to this library?

**Comment by dargmuesli** [comment]
Closing due to missing response.
