### ISSUE TITLE
Typed cookie id's

### ISSUE THREAD

**Issue by BlueBazze** [dargmuesli/nuxt-cookie-control#209]
### Describe the feature

Would be nice with having cookies typed.

I wanna know if this is wanted, before making any pr.

```ts
const cookies = [
  {
    id: "auth-token",
    name: "Auth token",
    isPreselected: true,
    description: "This cookie is used to authenticate the user.",
  },
  {
    id: "XSRF-TOKEN",
    name: "CSRF token",
    isPreselected: true,
    description: "This cookie is used to prevent CSRF attacks.",
  },
] as const;

// This is a type that represents the id's of the `cookies` array
type CookieId =  typeof cookies[number]["id"];


const rr: CookieId = "auth-token"
```

I am working on a composable for my project, i'd like to have some kind of selector for which cookie i am targeting with the composable.
Having the cookie id's as string literals instead of being typed as strings would catch misspelling.

It would probably not be anything major, just a new types file, a generator for this typing would be fairly small probably 10 lines.

### Additional information

- [X] Would you be willing to help implement this feature?

### Final checks

- [X] Check existing [discussions](https://github.com/nuxt/framework/discussions) and [issues](https://github.com/nuxt/framework/issues).

**Comment by dargmuesli** [comment]
Looks good to me

**Comment by dargmuesli** [comment]
Migrating to `runtimeConfig` looks good to me, the file output was implemented because this module was one of the first to migrate to Nuxt 3, at a time at which recipes or other documentations were not available yet. Do you want to create a separate PR for that?

**Comment by BlueBazze** [comment]
Sorry, was on another task. I see that you already did it - Well done.

**Comment by dargmuesli** [comment]
I didn't manage to get `runtimeConfig` running though due to typing issues. The linter sourced from `.nuxt` (`string` properties only) and `types` (proper types) which lead to type incompatibilities. Maybe you can figure out a way to have correct types in all places.

**Comment by BlueBazze** [comment]
I'll take a look within the next week

**Comment by BlueBazze** [comment]
@dargmuesli Done, fixed with
```ts
declare module '@nuxt/schema' {
  interface PublicRuntimeConfig {
    cookieControl: ModuleOptions
  }
}
```
I also moved it to public runtime config. Since the plugin is being run on the client side aswell.
In case you want to change it to the non-public runtime config later, just simply remove the "Public" part of "PublicRuntimeConfig"
