### ISSUE TITLE
Playground not building

### ISSUE THREAD

**Issue by bobrov-site** [dargmuesli/nuxt-cookie-control#219]
### Environment

pnpm install && pnpm run dev

### Reproduction

Go to https://stackblitz.com/github/dargmuesli/nuxt-cookie-control?file=playground%2Fapp.vue
Get error Failed to install dependencies

### Describe the bug

I want to see a playground or just demo for this project. I found link  https://stackblitz.com/github/dargmuesli/nuxt-cookie-control?file=playground%2Fapp.vue and this link not wrapped.

**Comment by dargmuesli** [comment]
Works for me still: 
![image](https://github.com/dargmuesli/nuxt-cookie-control/assets/4778485/f8287499-a2dd-4767-a729-8fa5bbc1250d)
Please provide additional information that allows me to reproduce the issue.

**Comment by bobrov-site** [comment]
https://youtu.be/8ZORgfFZOiQ

Trying from safari

**Comment by dargmuesli** [comment]
Could you share the full error here? It's not possible to spot fully shortly before the video ends.

**Comment by bobrov-site** [comment]
# This is a non-commercial version of StackBlitz.
# If you’re using this for business purposes, please purchase a license here.

~/projects/llqiqgbok.github
❯ pnpm install && pnpm run dev
[callSiteLocation@
depd@
../node_modules/.pnpm/agentkeepalive@4.2.1/node_modules/agentkeepalive/lib/agent.js@
@
../node_modules/.pnpm/agentkeepalive@4.2.1/node_modules/agentkeepalive/index.js@
@
../node_modules/.pnpm/@pnpm+network.agent@0.1.0/node_modules/@pnpm/network.agent/dist/agent.js@
@
../node_modules/.pnpm/@pnpm+network.agent@0.1.0/node_modules/@pnpm/network.agent/dist/index.js@
@
../network/fetch/lib/fetchFromRegistry.js@
@
../network/fetch/lib/index.js@
@
../env/plugin-commands-env/lib/node.js@
@
../env/plugin-commands-env/lib/downloadNodeVersion.js@
@
../env/plugin-commands-env/lib/envRemove.js@
@
../env/plugin-commands-env/lib/env.js@
@
../env/plugin-commands-env/lib/index.js@
@
lib/main.js@
@
lib/errorHandler.js@
@
@]

Node.js 18.20.3

~/projects/llqiqgbok.github 1s
❯

**Comment by bobrov-site** [comment]
@dargmuesli this is all I have from terminal

**Comment by dargmuesli** [comment]
hmm, this seems to be related to stackblitz, not this project as you can see all builds are green, even on mac and with node 18, which is currently in use by stackblitz. Here are two links to similar previous issues, which might help you debug:

- https://github.com/npm/cli/issues/2818
- https://stackoverflow.com/questions/68618743/cannot-find-module-agentkeepalive-when-updating-npm-to-7-20-3

Maybe try running `pnpm add agentkeepalive`? I'm afraid I can't help any further.

**Comment by dargmuesli** [comment]
If you find any other information that point to this project, this issue can be reopened.
