### ISSUE TITLE
Chinese locale used in `zh-CN` format, while all other languages have 2-character codes

### ISSUE THREAD

**Issue by codeflorist** [dargmuesli/nuxt-cookie-control#243]
### Environment

-

### Reproduction

-

### Describe the bug

`zh-CN` is the only language code used in this locale-code, while all other languages are using the normal 2-character locale format (e.g. `en`, `de`, etc.). Is there any special reason for this, or is this a bug?

It gets a bit problematic, if the website uses the normal 2-character language codes sitewide (`zh` for China).

**Comment by dargmuesli** [comment]
I think it was just submitted as such, but I think the name can be shortened if there is no other Chinese language variant locale.

**Comment by codeflorist** [comment]
I researched a bit.

The 2-character code is ISO 639-1.

The 4-character code is a possible variant of the IETF language tag. It can have many possible suffixes for all languages -  mainly country-codes, but also area-codes, dialects, etc.

So `zh-CN` would be _Chinese (China)_, while `zh-TW` would be _Chinese (Taiwan)_. And `en-GB` is _English (Great Britain)_, while `en_US` is `English (US)`.

For consistency, and because it's the most widely used format in webdev, i would suggest changing the chinese code to `zh`.

It would still prove problematic for a minority of sites using other formats, but that is also true for all other languages. I guess no one would use a mixture of formats as it is currently the case.

**Comment by dargmuesli** [comment]
Yup, would you submit a PR for this? :)

**Comment by codeflorist** [comment]
> Yup, would you submit a PR for this? :)

Sure! 😊👍

I've just created a pull request for it.

I guess, this would be a breaking change for those currently using `zh-CN` though.
