### ISSUE TITLE
Setting the `colors` option to `false` causes plugin not to run

### ISSUE THREAD

**Issue by madebyfabian** [dargmuesli/nuxt-cookie-control#31]
### Environment

```bash
------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.1.1`
- Nitro Version:    `2.0.0`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------
```

### Reproduction

https://stackblitz.com/edit/github-y7t61d?file=playground%2Fnuxt.config.ts

### Describe the bug

The docs suggest you can define `colors` to false, to not use color variables. When doing this though, it causes the whole plugin (overlay) to just not load. No error messages either.

**Comment by madebyfabian** [comment]
Seems like caused by

https://github.com/dargmuesli/nuxt-cookie-control/blob/401986c080f349570a41898bcdcea71a749dfcd2/src/runtime/components/CookieControl.vue#L6

https://github.com/dargmuesli/nuxt-cookie-control/blob/401986c080f349570a41898bcdcea71a749dfcd2/src/runtime/components/CookieControl.vue#L34

**Comment by dargmuesli** [comment]
Thank you for the bug report, @madebyfabian! #33 should fix this issue.
