### ISSUE TITLE
Cookies not set

### ISSUE THREAD

**Issue by pieer** [dargmuesli/nuxt-cookie-control#36]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.16.0`
- Nuxt Version:     `3.1.2`
- Nitro Version:    `2.1.1`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `app`, `runtimeConfig`, `modules`, `extends`, `auth`, `vue`, `vite`, `css`, `tailwindcss`, `image`
- Runtime Modules:  `@nuxt/content@2.4.3`, `@pinia/nuxt@0.4.6`, `@nuxtjs/tailwindcss@6.3.1`, `nuxt-icons@3.1.0`, `@nuxt/image-edge@1.0.0-27919678.2f5b64b`, `@formkit/nuxt@1.0.0-beta.14`, `@vueuse/nuxt@9.12.0`, `@sidebase/nuxt-auth@0.4.0-alpha.5`, `nuxt-headlessui@1.1.1`, `@dargmuesli/nuxt-cookie-control@4.3.0`
- Build Modules:    `-`

### Reproduction

Nuxt.config.ts

['@dargmuesli/nuxt-cookie-control', {
      colors: false,
      isControlButtonEnabled: false,
      cookies: {
        necessary: [{
          id: 'necessary',
          name: 'Website and API',
          description: 'Essential cookies for the website and API to work properly.',
          targetCookieIds: ['cookie_control_consent', 'cookie_control_enabled_cookies', 'MuxData', 'next-auth'],
          initialState: false
        }],
        optional: [{
          id: 'google-analytics',
          name: 'Google Analytics',
          description: 'Helps us understand user behavior and optimize our services.',
          targetCookieIds: ['_ga', '_gat_<token>'],
          initialState: true,
        }],
      }
    }]

### Describe the bug

No cookies are set when I accept

### Additional context

The Watch for isConsentGiven not triggered in CookieControl.vue (line 373) in library but I can see that it's triggered in my code when I create my own watch.

**Comment by dargmuesli** [comment]
Hello there, please format code examples using the correct markdown syntax so that the code is syntax-highlighted and has proper indentation. Please also provide a link to stackblitz as required by the issue template for a minimal reproduction, then we can reopen the issue.
