### ISSUE TITLE
feat: don't include the css vars ponyfill in build when disabled

### ISSUE THREAD

**Issue by madebyfabian** [dargmuesli/nuxt-cookie-control#37]
### Describe the feature

Hey there,
I am using v3.4.0 and setting the css vars ponyfill integration to `false`: 

```ts
export default defineNuxtConfig({
	modules: [
		'@dargmuesli/nuxt-cookie-control',
	],

	// @dargmuesli/nuxt-cookie-control
	cookieControl: {
		isCssPolyfillEnabled: false,
	},
})

```

Though in my build logs, it's getting integrated into the client when `nuxt generate`:

```bash
// ...
.nuxt/dist/client/_nuxt/css-vars-ponyfill.esm.495bc596.js   31.91 kB │ gzip: 10.18 kB
// ...
```

I can also see it in the build analyzer, taking a large chunk of my app 😄
![Bildschirm­foto 2023-02-06 um 06 25 33](https://user-images.githubusercontent.com/32813692/216890447-3300b722-046f-449a-9988-1035568f169b.jpg)

### Additional information

- [X] Would you be willing to help implement this feature?

### Final checks

- [X] Check existing [discussions](https://github.com/nuxt/framework/discussions) and [issues](https://github.com/nuxt/framework/issues).

**Comment by dargmuesli** [comment]
That's a good find! Of course, the ponyfill should not be included if disabled. Also great to see that you'd be willing to help implement this feature. You've got a "go" from me! :)

**Comment by madebyfabian** [comment]
Interesting thing, I've cloned and installed the module locally and it does not inject the polyfill package inside the `nuxt analyze` build, even if I set the option to `true`. So I guess it adds it only to the module's user?

I saw that in the next major of the plugin you rewrote functionality and made this option it `false` by default. Let's go a step further and remove the package completely and if a user actively decides they need the polyfill (which will be a fairly small amount) they should just install the package as a peer dep and activate the option.

This approach is suggested by @danielroe (at least I read somewhere he would do it that way). So this cleans up your module and people really needing a polyfill also have the benefit of package version control + which polyfill they want to use, so multiple benefits here.

What do you think?

**Comment by dargmuesli** [comment]
Sounds logical to me :+1:

I suspect my personal issue with using pnpm would then be that I'd need to ignore this optional dependency in the projects in which I use this cookie module. Somehow warns for missing optional dependencies, which I googled a few times now but haven't found a proper solution for yet. Maybe I'm just misunderstanding how pnpm works regarding optional peer dependencies... do you know anything about that? I haven't had the chance to talk to someone about that yet.

**Comment by dargmuesli** [comment]
For example, [here](https://github.com/maevsi/maevsi/blob/a11d740d3e50b6ef9f8a8c7e7d7fa91d2100265d/nuxt/package.json#L161), I ignore `webpack` because this cookie module specifies webpack as optional peer dependency.

**Comment by madebyfabian** [comment]
@dargmuesli Okay I see what you mean. Just recently made the switch to pnpm so I'm not an expert. Does it spit out an active warning? For my project I am getting this when doing a fresh install:

```
Peer dependencies that should be installed:
  @babel/core@^7.0.0-0            vue@">=3.2.0 <4.0.0"            
  @types/node@">=18.0.6 <19.0.0"  webpack@">=5.0.0 <6.0.0"        
  @unhead/vue@>=1.0.10            ws@>=8  
```

I do not and everything works fine. So I think the benefit of not having this large polyfill module even though disabled by users in *every* project using `nuxt-cookie-control` is higher than this warning, what do you think? And maybe the warning can be removed in some way, let's research that.

**Comment by madebyfabian** [comment]
Update: I was referring to this tweet https://twitter.com/danielcroe/status/1622688665313939473?s=46&t=z5kQH44uBSu0wk6SvBz6hw but this is about a module that definitely is required, which is not the case for this module

**Comment by dargmuesli** [comment]
Right, one is fine with ignoring those warnings. Still, there should be a way to work around these warnings if they are incorrect. I'd expect to be able to ignore `webpack` as a peer dependency of `@dargmuesli/nuxt-cookie-control` only, not webpack in general, but I don't think that's possible. I'm using pnpm for a few months now only as well.
My educated guess is that we need a [dynamic import](https://vitejs.dev/guide/features.html#dynamic-import) for the ponyfill.

**Comment by dargmuesli** [comment]
Well, I rather meant something like a conditional import. But how should vite know if a condition is ever matched? I'm pretty sure it cannot. So we'd need to somehow give the bundler instructions on whether to include a package or not. I'm not experienced enough with bundlers yet to know how that would work. I'll try to contact Daniel to maybe get a pointer into the right direction.

**Comment by madebyfabian** [comment]
@dargmuesli Thanks for your efforts on this!

**Comment by madebyfabian** [comment]
Awesome, thanks!
