### ISSUE TITLE
docs(readme): explain watcher for reactive variables

### ISSUE THREAD

**Issue by liamcharmer** [dargmuesli/nuxt-cookie-control#45]
### Describe the feature

Is there a way that when the user accepts the cookies, we can have an event listener like

    <CookieControl locale="en" @accepted="cookiesAccepted" />
    
   Thank you!

### Additional information

- [ ] Would you be willing to help implement this feature?

### Final checks

- [X] Check existing [discussions](https://github.com/nuxt/framework/discussions) and [issues](https://github.com/nuxt/framework/issues).

**Comment by dargmuesli** [comment]
You can always check for changes on enabled cookies [as explained in the migration instructions](https://github.com/dargmuesli/nuxt-cookie-control/releases/tag/2.0.0).

**Comment by liamcharmer** [comment]
> You can always check for changes on enabled cookies [as explained in the migration instructions](https://github.com/dargmuesli/nuxt-cookie-control/releases/tag/2.0.0) or on `isConsentGiven`.

Im so sorry, I ticked the box saying I checked existing idscussions etc.. and i didn't even read the migration instructions. My Apologies and thank you so much for the direction!

**Comment by dargmuesli** [comment]
No worries, we should put those instructions into the README.
