### ISSUE TITLE
Rollup failed to resolve import on Windows 11 during build

### ISSUE THREAD

**Issue by Daeghun** [dargmuesli/nuxt-cookie-control#73]
### Environment

```
- Operating System: `Windows_NT`
- Node Version:     `v16.19.1`
- Nuxt Version:     `3.3.1`
- Nitro Version:    `2.3.1`
- Package Manager:  `npm@9.6.2`
- Builder:          `vite`
- User Config:      `modules`, `cookieControl`
- Runtime Modules:  `@dargmuesli/nuxt-cookie-control@5.2.0`
- Build Modules:    `-`
```

### Reproduction

Using Windows create new bare project:

```
npx nuxi init newproject
npm install
```

Add package with npm (or yarn):

`npm i -D @dargmuesli/nuxt-cookie-control`

Follow the steps in README to add the module 
- added configuration on nuxt.config.js
- added component to root app.vue

Build the project using
`npm run build`

### Describe the bug

Build fails with the following error:

```
 ERROR  [vite]: Rollup failed to resolve import "C:UsersusernameProjects                                                                                                     
ewproject
ode_modules@dargmuesli
untimecomposables" from "C:/Users/username/Projects/newproject/app.vue?vue&type=script&setup=true&lang.ts".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`

  ewproject
  ode_modules@dargmuesli
untimecomposables" from "C:/Users/username/Projects/newproject/app.vue?vue&type=script&setup=true&lang.ts".
  This is most likely unintended because it can break your application at runtime.
  If you do want to externalize this module explicitly add it to
  `build.rollupOptions.external`
  at onRollupWarning (/C:/Users/username/Projects/newproject/node_modules/vite/dist/node/chunks/dep-ca21228b.js:44792:19)
  at onwarn (/C:/Users/username/Projects/newproject/node_modules/vite/dist/node/chunks/dep-ca21228b.js:44562:13)
  at Object.onwarn (/C:/Users/username/Projects/newproject/node_modules/rollup/dist/es/shared/node-entry.js:25103:13)
  at ModuleLoader.handleInvalidResolvedId (/C:/Users/username/Projects/newproject/node_modules/rollup/dist/es/shared/node-entry.js:23778:26)
  at /C:/Users/username/Projects/newproject/node_modules/rollup/dist/es/shared/node-entry.js:23738:26
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

For some reason it seems that Windows path got truncated (backslahes removed)

**Comment by dargmuesli** [comment]
The build on master is currently running fine, including the build in Windows. If you'd like someone to look into it, please provide a minimal reproduction as required in the issue template.

**Comment by robertorinaldi-dev** [comment]
Same problem

**Comment by Daeghun** [comment]
@dargmuesli I believe the issue is not in ability building the repository, but in vite manipulations during nuxt build.

As a minimal example, here is zip of the project. Not that this is just bare nuxt project with cookit control lib:

[nuxt-cookie-control-bug.zip](https://github.com/dargmuesli/nuxt-cookie-control/files/11050995/nuxt-cookie-control-bug.zip)

**Comment by dargmuesli** [comment]
Thank you for the additional data. I do not have access to a Windows machine though and would need a reproduction that I can see fail, like a failing test here on GitHub actions. So you can fork this repo and try to change the playground configuration to make it fail for the windows build :bulb: 
Also, try to remove the lockfile and recreate it.

**Comment by dargmuesli** [comment]
799eea67a3fbf88ae237858b5b5f9bb475093b88
