### ISSUE TITLE
fix(vite): support iframe blocking

### ISSUE THREAD

**Issue by marco-land** [dargmuesli/nuxt-cookie-control#79]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.19.0`
- Nuxt Version:     `3.2.2`
- Nitro Version:    `2.2.2`
- Package Manager:  `yarn@1.22.17`
- Builder:          `vite`
- User Config:      `app`, `css`, `vite`, `modules`, `sanity`, `nitro`, `hooks`
- Runtime Modules:  `@nuxtjs/sanity@1.6.0`, `@pinia/nuxt@0.4.6`, `@vueuse/nuxt@9.12.0`, `@nuxtjs/device@3.0.0`, `@dargmuesli/nuxt-cookie-control@5.2.2`
- Build Modules:    `-`

### Reproduction

`nuxt.config.ts` settings this option `isIframeBlocked: true`

### Describe the bug

Setting `isIframeBlocked: true` does not block iFrames (e.g. Vimeo Player)

**Comment by dargmuesli** [comment]
Please setup a [minimal reproduction](https://stackblitz.com/github/dargmuesli/nuxt-cookie-control?file=playground%2Fapp.vue) using StackBlitz as required by the issue template :pray:

**Comment by marco-land** [comment]
Okay, here is [an example](https://stackblitz.com/edit/github-lvr4ve?file=playground%2Fnuxt.config.ts).

**Comment by dargmuesli** [comment]
Gotcha, thanks! Actually, iframe blocking is not yet implemented for vite, only for webpack: https://github.com/dargmuesli/nuxt-cookie-control/blob/cab857401082393378ab280b0502913e1489466a/src/module.ts#L102 Background being that Nuxt 2 used webpack as its bundler.
Pull requests welcome! :heart:

**Comment by dargmuesli** [comment]
Additional info: the iframe block setting `initialState` was never properly implemented for cookies and is scheduled to be removed in the upcoming version 6 of this module to avoid confusion. The whole iframe blocking topic needs a proper implementation, that is. This could be done before v6, reverting any removal in that version. Or v6 happens first, avoiding further confusion, with a potential new implementation coming at a later time.

**Comment by marco-land** [comment]
If anyone else encounters this problem, I am using a solution similar to [this](https://stackblitz.com/edit/github-lvr4ve-tfswv6?file=playground%2Fnuxt.config.ts,playground%2Fapp.vue) for now, here the [full preview](https://githublvr4vetfswv6-tr4l--3000.local-credentialless.webcontainer.io/).

**Comment by dargmuesli** [comment]
Would it be an option for you to create a PR containing your implementation generalized for others to use it as well?
