### ISSUE TITLE
The required node version (20) is incompatible with other nuxt packages

### ISSUE THREAD

**Issue by semiaddict** [dargmuesli/nuxt-cookie-control#97]
### Environment

Nuxi 3.4.3                                                                                                                                                                                               

Nuxt project info:                                                                                                                                                                                       

------------------------------
- Operating System: Linux
- Node Version:     v20.1.0
- Nuxt Version:     3.4.3
- Nitro Version:    2.3.3
- Package Manager:  npm@9.6.4
- Builder:          vite
- User Config:      modules, app, css, content, search, image, colorMode, matomo, cookieControl, vite
- Runtime Modules:  @nuxt/content@2.6.0, @nuxt/image-edge@1.0.0-28050764.aaee7ac, @nuxtjs/color-mode@3.2.0, @dargmuesli/nuxt-cookie-control@5.8.0
- Build Modules:    -
------------------------------

### Reproduction

There is no repro, as the problem occurs when installing after upgrading node to 20 to meet the new requirements added in https://github.com/dargmuesli/nuxt-cookie-control/commit/dbf29b552a98fe59c0027677de0c96705edec296 .

### Describe the bug

Node 20 is set as a requirement for [v5.8.0](https://github.com/dargmuesli/nuxt-cookie-control/releases/tag/5.8.0).
Most other Nuxt packages have their Node requirement set to versions below 20. This is also the case for core packages such as @nuxt/kit, @nuxt/schema and nitropack.

Thus after upgrading node to 20, I get the log messages below.

### Logs

```shell
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@nuxt/kit@3.4.1',
npm WARN EBADENGINE   required: { node: '^14.18.0 || ^16.10.0 || ^17.0.0 || ^18.0.0 || ^19.0.0' },
npm WARN EBADENGINE   current: { node: 'v20.1.0', npm: '9.6.4' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@nuxt/schema@3.4.1',
npm WARN EBADENGINE   required: { node: '^14.18.0 || ^16.10.0 || ^17.0.0 || ^18.0.0 || ^19.0.0' },
npm WARN EBADENGINE   current: { node: 'v20.1.0', npm: '9.6.4' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@nuxt/image-edge@1.0.0-28050764.aaee7ac',
npm WARN EBADENGINE   required: { node: '^14.16.0 || ^16.11.0 || ^17.0.0 || ^18.0.0 || ^19.0.0' },
npm WARN EBADENGINE   current: { node: 'v20.1.0', npm: '9.6.4' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'nitropack@2.3.3',
npm WARN EBADENGINE   required: { node: '^14.16.0 || ^16.11.0 || ^17.0.0 || ^18.0.0 || ^19.0.0' },
npm WARN EBADENGINE   current: { node: 'v20.1.0', npm: '9.6.4' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'nypm@0.2.0',
npm WARN EBADENGINE   required: { node: '^14.16.0 || ^16.10.0 || ^17.0.0 || ^18.0.0 || ^19.0.0' },
npm WARN EBADENGINE   current: { node: 'v20.1.0', npm: '9.6.4' }
npm WARN EBADENGINE }
```

**Comment by dargmuesli** [comment]
https://github.com/dargmuesli/nuxt-cookie-control/releases/tag/5.8.5

**Comment by semiaddict** [comment]
Thank you very much @dargmuesli. v5.8.5 fixed the issue for me.
BTW, thank you for this great module. It's a lifesaver!
